"use strict";
let cars = ["BMW", "Audi", "Mercedes", "Toyota", "Honda", "Suzuki", "Hyundai", "Kia", "Mazda", "Nissan"];
console.log(cars);
console.log();
let countries = ["Pakistan", "India", "China", "USA", "UK", "Canada", "Australia", "New Zealand", "Japan", "South Korea"];
console.log(countries);
console.log();
let fruits = ["Apple", "Banana", "Mango", "Orange", "Grapes", "Pineapple", "Watermelon", "Strawberry", "Peach", "Pear"];
console.log(fruits);
console.log();
